
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button btnShow;
	private global::Gtk.Button btnRandom;
	private global::Gtk.Button btnBackward;
	private global::Gtk.Button btnForward;
	private global::Gtk.FileChooserButton filechooserbutton1;
	private global::Gtk.Button btnClose;
	private global::Gtk.Image pixbox;
	private global::Gtk.Statusbar statusbar1;
	private global::Gtk.Label lblOut;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 430;
		this.HeightRequest = 460;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.AllowShrink = true;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 5;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnShow = new global::Gtk.Button ();
		this.btnShow.CanFocus = true;
		this.btnShow.Name = "btnShow";
		this.btnShow.UseUnderline = true;
		this.btnShow.Label = global::Mono.Unix.Catalog.GetString ("Show");
		this.hbox1.Add (this.btnShow);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnShow]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnRandom = new global::Gtk.Button ();
		this.btnRandom.CanFocus = true;
		this.btnRandom.Name = "btnRandom";
		this.btnRandom.UseUnderline = true;
		this.btnRandom.Label = global::Mono.Unix.Catalog.GetString ("Random");
		this.hbox1.Add (this.btnRandom);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnRandom]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnBackward = new global::Gtk.Button ();
		this.btnBackward.CanFocus = true;
		this.btnBackward.Name = "btnBackward";
		this.btnBackward.UseUnderline = true;
		this.btnBackward.Label = global::Mono.Unix.Catalog.GetString ("Backward");
		this.hbox1.Add (this.btnBackward);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnBackward]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnForward = new global::Gtk.Button ();
		this.btnForward.CanFocus = true;
		this.btnForward.Name = "btnForward";
		this.btnForward.UseUnderline = true;
		this.btnForward.Label = global::Mono.Unix.Catalog.GetString ("Forward");
		this.hbox1.Add (this.btnForward);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnForward]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.filechooserbutton1 = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(2)));
		this.filechooserbutton1.Events = ((global::Gdk.EventMask)(16));
		this.filechooserbutton1.Name = "filechooserbutton1";
		this.hbox1.Add (this.filechooserbutton1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.filechooserbutton1]));
		w5.Position = 4;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnClose = new global::Gtk.Button ();
		this.btnClose.CanFocus = true;
		this.btnClose.Name = "btnClose";
		this.btnClose.UseUnderline = true;
		this.btnClose.Label = global::Mono.Unix.Catalog.GetString ("Close");
		this.hbox1.Add (this.btnClose);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnClose]));
		w6.Position = 5;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.pixbox = new global::Gtk.Image ();
		this.pixbox.WidthRequest = 400;
		this.pixbox.HeightRequest = 400;
		this.pixbox.Events = ((global::Gdk.EventMask)(36));
		this.pixbox.Name = "pixbox";
		this.vbox1.Add (this.pixbox);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.pixbox]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.lblOut = new global::Gtk.Label ();
		this.lblOut.Name = "lblOut";
		this.lblOut.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.statusbar1.Add (this.lblOut);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.lblOut]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 432;
		this.DefaultHeight = 485;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
